- example.main.scss
- objects/_objects.pack.scss
> [refs #0098] Bring in initial pack object

- bower.json
see #139 
did I miss anything?
> [refs #139] add ignore to bower.json

- .npmignore
- CONTRIBUTING.md
- package.json
- test/_tools.font-size.scss
- test/_tools.rem.scss
- test/_utilities.widths.scss
- test/run.js
Compliments #133 
So I thought I would go ahead and throw the initial setup together so everyone can see what the code could look like.
All tests are green 😄
> Adding unit tests

- objects/_objects.crop.scss
> [objects.crop] Move config var to the top of the file

- .stylelintrc
- components/_example.components.buttons.scss
- example.main.scss
- generic/_generic.shared.scss
- objects/_objects.block.scss
- objects/_objects.crop.scss
- objects/_objects.ratio.scss
- objects/_objects.wrapper.scss
- package.json
- settings/_example.settings.global.scss
- tools/_tools.font-size.scss
- utilities/_utilities.spacing.scss
> Add stylelint.

- generic/_generic.shared.scss
> [refs #170] Add missing comma

- utilities/_utilities.widths.scss
> [utilities.widths] Proper trumps (add !important)

- settings/_example.settings.global.scss
300 seconds is a bit too much 😄
> Fix transition-duration value

- objects/_objects.pack.scss
> [refs #234] Rename pack objects reverse modifier

- objects/_objects.layout.scss
> [refs #266] Add --auto modifier for layout object

- LICENSE
> Update year in license file

- objects/_objects.layout.scss
#264 
Related to the discussion in #253
> [refs #264] Add equal-height modifier

- README.md
This adds instructions on how to add inuitcss as a dependency using yarn client for the npm-registry.
> Add yarn instructions to README.

- objects/_objects.crop.scss
I add a [CodePen](http://codepen.io/florianbouvot/pen/GmMJoE?editors=1100) with some test and it seems good.
> [refs #278] Add fill modifier

- objects/_objects.flag.scss
This closes https://github.com/inuitcss/inuitcss/pull/322 (the original PR).
@rowild this is the rebased, updated branch and version. I also fixed some whitespace issues that let the tests fail and attributed it to your commit.
> [refs #322] Update comment description for flag object

- example.main.scss
> [refs #318] Point out the danger of offsets

- circle.yml
This fixes the CircleCI environment and closes #336.
> [refs #336] Fix CircleCI test build environment.

- CHANGELOG.md
- CONTRIBUTING.md
This PR would make #229 obsolete.
@inuitcss/core We can talk about naming of the categories of changes and the formatting here. 
I think, contentwise I covered everything important. Although we definitely should be even more explicit in future versions when it comes to filling out the `CHANGELOG.md` alongside each Pull Request. But for this state of the project, I think this will suffice.
> [refs #218] Add CHANGELOG

- CHANGELOG.md
- objects/_objects.wrapper.scss
> [refs #299] Remove wrapper modifier

- CHANGELOG.md
- objects/_objects.crop.scss
> [refs #298] Add more position modifier for crop object

- CHANGELOG.md
- objects/_objects.crop.scss
- objects/_objects.ratio.scss
> [refs #276] Decimal ratios for crop and ratio object
